import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Tick from "@/assets/icons/circle-tick.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        {children}
        {modal}
        {/* <div className="fixed right-4 bottom-4 z-1000 w-[20rem] bg-green-500 text-white px-4 py-2 rounded-lg flex gap-2 items-center">
          <Tick className="size-5" />
          <span>Successfully added new course</span>
        </div> */}
      </body>
    </html>
  );
}
